version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
     - REACT_APP_BACKEND_URL=http://16.171.176.162:5000/api
    

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres      # Replace with your AWS RDS username
      - DB_PASSWORD=Ridham2001  # Replace with your AWS RDS password
      - DB_NAME=todoapp     # Replace with your AWS RDS database name
      - DB_HOST=demo-postgres.cjwoqqko69er.eu-north-1.rds.amazonaws.com      # Replace with your AWS RDS endpoint (e.g., db-instance-name.region.rds.amazonaws.com)
      - DB_PORT=5432
  # No 'db' service since we're using AWS RDS now.
